# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_prelucrare = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_prelucrare.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_prelucrare.setObjectName("pushButton_prelucrare")
        self.gridLayout_2.addWidget(self.pushButton_prelucrare, 2, 0, 1, 1)
        self.label_nume_imagine = QtWidgets.QLabel(self.centralwidget)
        self.label_nume_imagine.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nume_imagine.setObjectName("label_nume_imagine")
        self.gridLayout_2.addWidget(self.label_nume_imagine, 2, 1, 1, 1)
        self.label_drag_drop = QtWidgets.QLabel(self.centralwidget)
        self.label_drag_drop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_drag_drop.setObjectName("label_drag_drop")
        self.gridLayout_2.addWidget(self.label_drag_drop, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_prelucrare.setText(_translate("MainWindow", "Prelucrare"))
        self.label_nume_imagine.setText(_translate("MainWindow", "Nume Imagine --  "))
        self.label_drag_drop.setText(_translate("MainWindow", "Drag the image here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
